from collections.abc import Callable, Iterator
from enum import Enum
from pathlib import Path
from typing import Any, TypeVar

class EggReplayError(Exception): ...
class FixtureError(EggReplayError): ...
class MatchError(EggReplayError): ...
class NetworkError(EggReplayError): ...
class ConfigurationError(EggReplayError): ...
class RegressionError(EggReplayError): ...

class MatcherProfile(str, Enum):
    STRICT: MatcherProfile
    PRACTICAL: MatcherProfile

class ConsumptionMode(str, Enum):
    ONCE: ConsumptionMode
    REPEAT_LAST: ConsumptionMode
    UNLIMITED: ConsumptionMode

class RecordMode(str, Enum):
    SEALED: RecordMode
    ONCE: RecordMode
    APPEND_NEW: RecordMode
    RE_RECORD: RecordMode

class WebSocketRedaction(str, Enum):
    WHOLE_MESSAGE: WebSocketRedaction
    CLOSE_REASON: WebSocketRedaction

class Request:
    @property
    def method(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> list[tuple[str, str]]: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    def to_dict(self) -> dict[str, Any]: ...

class Response:
    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    def to_dict(self) -> dict[str, Any]: ...

class FlowErrorInfo:
    @property
    def category(self) -> str: ...
    @property
    def phase(self) -> str: ...
    @property
    def message(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class Flow:
    @property
    def id(self) -> str: ...
    @property
    def request(self) -> Request: ...
    @property
    def response(self) -> Response | None: ...
    @property
    def error(self) -> FlowErrorInfo | None: ...
    @property
    def outcome(self) -> dict[str, Any]: ...
    def to_dict(self) -> dict[str, Any]: ...

class FlowIterator(Iterator[Flow]):
    def __iter__(self) -> FlowIterator: ...
    def __next__(self) -> Flow: ...

class BodyReader(Iterator[bytes]):
    @property
    def length(self) -> int: ...
    @property
    def sha256(self) -> str: ...
    def read(self, size: int) -> bytes: ...
    def read_all(self, max_bytes: int | None = ...) -> bytes: ...
    def close(self) -> None: ...
    def __enter__(self) -> BodyReader: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    def __iter__(self) -> BodyReader: ...
    def __next__(self) -> bytes: ...

class Fixture:
    def __init__(self, path: str | Path) -> None: ...
    @property
    def manifest(self) -> dict[str, Any]: ...
    @property
    def extension_metadata(self) -> list[dict[str, Any]]: ...
    def websocket_summary(self) -> dict[str, Any] | None: ...
    def scenario_summary(self) -> dict[str, Any] | None: ...
    def stream_summary(self) -> dict[str, Any] | None: ...
    def iter_flows(self) -> FlowIterator: ...
    def flow(self, flow_id: str) -> Flow | None: ...
    def open_body(self, flow_id: str, side: str) -> BodyReader: ...

class DiffFinding:
    @property
    def kind(self) -> str: ...
    @property
    def field(self) -> str: ...
    @property
    def baseline(self) -> str: ...
    @property
    def candidate(self) -> str: ...

class RegressionReport:
    @staticmethod
    def from_json(json: str) -> RegressionReport: ...
    @property
    def success(self) -> bool: ...
    @property
    def finding_count(self) -> int: ...
    @property
    def baseline_flow_ids(self) -> list[str]: ...
    @property
    def findings(self) -> list[DiffFinding]: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class StreamTimingMode:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...

class RedactionConfig:
    def __init__(
        self,
        headers: list[str] | None = ...,
        query_keys: list[str] | None = ...,
        json_paths: list[str] | None = ...,
    ) -> None: ...
    def to_dict(self) -> dict[str, list[str]]: ...

class ComparisonPolicy:
    def __init__(
        self,
        compare_stream_events: bool = ...,
        cadence_tolerance_ns: int | None = ...,
        compare_sse: bool = ...,
        sse_ignored: list[str] | None = ...,
        websocket_cadence_tolerance_ns: int | None = ...,
    ) -> None: ...
    @property
    def compare_stream_events(self) -> bool: ...
    @property
    def compare_sse(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...

class RouteSpecification:
    def __init__(self, kind: str, target: str | None = ...) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def target(self) -> str | None: ...
    def to_dict(self) -> tuple[str, str | None]: ...

class WebSocketOptions:
    def __init__(
        self,
        recording_enabled: bool = ...,
        cadence_tolerance_ns: int | None = ...,
        redaction_mode: str = ...,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class Server:
    @property
    def address(self) -> str: ...
    def is_closing(self) -> bool: ...
    async def aclose(self) -> None: ...
    async def wait(self) -> None: ...
    async def __aenter__(self) -> Server: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class FixtureContext:
    def __enter__(self) -> Server: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    async def __aenter__(self) -> Server: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

def record_policy(
    mode: RecordMode, *, fixture_exists: bool, upstream_configured: bool
) -> dict[str, Any]: ...

async def replay_server(
    fixture: Fixture,
    bind: str = ...,
    matcher_profile: str = ...,
    timing_mode: str = ...,
    max_body_bytes: int = ...,
    scenario_id: str | None = ...,
) -> Server: ...

async def recording_gateway(
    fixture_path: str,
    upstream: str,
    bind: str = ...,
    route: str = ...,
    record_mode: str = ...,
    websockets: bool = ...,
    max_body_bytes: int = ...,
) -> Server: ...

async def regress_flow(
    fixture: Fixture,
    flow_id: str,
    target: str,
    route: str = ...,
    max_body_bytes: int = ...,
    compare_sse: bool = ...,
    compare_stream_events: bool = ...,
    cadence_tolerance_ns: int | None = ...,
) -> RegressionReport: ...

def fixture_context(
    fixture_path: str | Path,
    *,
    record_mode: RecordMode | str | None = ...,
    upstream: str | None = ...,
    route: str = ...,
    bind: str = ...,
    websockets: bool = ...,
) -> FixtureContext: ...

_F = TypeVar("_F", bound=Callable[..., Any])
def use_fixture(
    fixture_path: str | Path,
    *,
    record_mode: RecordMode | str | None = ...,
    upstream: str | None = ...,
    route: str = ...,
    websockets: bool = ...,
) -> Callable[[_F], _F]: ...

def validate_matcher_profile(value: str) -> str: ...
def validate_consumption_mode(value: str) -> str: ...
def validate_record_mode(mode: str, fixture_exists: bool, upstream_configured: bool) -> tuple[str, bool]: ...
def validate_stream_timing(value: str) -> str: ...
async def async_value() -> int: ...
async def async_sleep(seconds: float) -> None: ...
def version() -> str: ...

__all__: list[str]
