from collections.abc import AsyncIterator, Iterator

import pytest

from . import Fixture, RegressionReport, Server

class RegressionAssertions:
    def compare(self, flow_id: str, target: str, **options: object) -> RegressionReport: ...
    async def acompare(self, flow_id: str, target: str, **options: object) -> RegressionReport: ...

def pytest_addoption(parser: pytest.Parser) -> None: ...
def pytest_configure(config: pytest.Config) -> None: ...
def eggreplay_fixture(request: pytest.FixtureRequest) -> Fixture: ...
def eggreplay_server(request: pytest.FixtureRequest) -> Iterator[Server]: ...
async def eggreplay_async_server(request: pytest.FixtureRequest) -> AsyncIterator[Server]: ...
def eggreplay_recorder(eggreplay_server: Server) -> Server: ...
async def eggreplay_async_recorder(eggreplay_async_server: Server) -> Server: ...
def eggreplay_report(eggreplay_fixture: Fixture) -> RegressionAssertions: ...
